### ISSUE TITLE
No instructions

### ISSUE THREAD

**Issue by ShadowOfPripyat** [0x-FADED/GTA-V-fwBoxStreamerboxVariable-and-decals-limit-Patch#1]
No instructions to install this patch. 
-Please add just one line

**Comment by 0x-FADED** [comment]
sorry for late reply but added it now

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by 0x-FADED** [comment]
fixed [here](https://github.com/0x-FADED/GTA-V-fwBoxStreamerVariable-and-decals-limit-Patch/commit/f57953481385b77a1415a35d7f6f501582183514)
